# Matrix transpose

In [1]:
import numpy as np
G = np.array(
    [
        [1, 0, 0, 1],
        [0, 1, 0, -1],
        [0, 0, 1, 1]
    ]
)


In [2]:
G1 = np.transpose(G)
G1


array([[ 1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0,  1],
       [ 1, -1,  1]])

# Matrix multiplication

In [3]:
G2 = np.dot(G, G1)
G2


array([[ 2, -1,  1],
       [-1,  2, -1],
       [ 1, -1,  2]])

# Matrix Inverse

In [5]:
G3 = np.linalg.inv(G2)
G3

array([[ 0.75,  0.25, -0.25],
       [ 0.25,  0.75,  0.25],
       [-0.25,  0.25,  0.75]])