In [1]:
import numpy as np

In [2]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr2 = arr1.reshape((1, -1))
print(arr2)

[[0 1 2 3 4 5 6 7 8 9]]


In [10]:
arr3 = np.array([[1], [2], [3]])
print(arr3)

[[1]
 [2]
 [3]]


(3, 1)

In [11]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr6 = np.arange(10, 20)
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
arr7 = np.arange(1, 21, 2)
arr7

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [16]:
arr8 = np.zeros(3)
arr8

array([0., 0., 0.])

In [17]:
arr9 = np.zeros((3, 3))
arr9

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr10 = np.pi * np.ones((3, 3))
arr10

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [21]:
# 生成0～1均匀分布的浮点型随机数组
arr1 = np.random.random((2, 5)) 
arr1

array([[0.83153815, 0.36788296, 0.31734158, 0.55827098, 0.85793271],
       [0.24415289, 0.02171126, 0.06497585, 0.28694831, 0.47916481]])

In [24]:
# 生成[10, 100)整型随机数组
arr2 = np.random.randint(10, 100, (1, 15))
arr2

array([[71, 13, 54, 36, 81, 65, 95, 86, 13, 15, 25, 47, 37, 23, 75]])

In [26]:
# 服从正态分布的随机数组
arr3 = np.random.normal(0, 1, (2, 3))
arr3

array([[ 1.62244454e+00,  4.61915701e-01, -1.24927646e+00],
       [-9.44886352e-03, -1.33827351e+00,  3.38172970e-04]])

In [29]:
arr1 = np.arange(10)
arr2 = arr1.reshape((5, 2))
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
import pandas as pd

In [31]:
# 创建字典
dic_v = {'a': 0, 'b': 0.25, 'c': 0.5, 'd': 0.75, 'e': 1}

In [32]:
sr = pd.Series(dic_v)
sr

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [33]:
import torch

In [34]:
v = torch.tensor([53, 64, 72, 82])
k = ['No.1', 'No.2', 'No.3', 'No.4']
sr = pd.Series(v, k)
sr

No.1    53
No.2    64
No.3    72
No.4    82
dtype: int64

In [37]:
sr.values

array([53, 64, 72, 82])

In [38]:
v1 = [53, 64, 72, 82]
i = ['No.1', 'No.2', 'No.3', 'No.4']
sr1 = pd.Series(v1, index= i)
sr1

No.1    53
No.2    64
No.3    72
No.4    82
dtype: int64

In [53]:
v2 = ['female', 'male', 'male', 'female']
i = ['No.1', 'No.2', 'No.3', 'No.4']
sr2 = pd.Series(v2, index= i)
sr2

No.1    female
No.2      male
No.3      male
No.4    female
dtype: object

In [57]:
sr2.loc['No.3']

'male'

In [56]:
sr2.iloc[2]

'male'

In [61]:
sr2.loc[['No.1', 'No.3']]

No.1    female
No.3      male
dtype: object

In [62]:
sr2.iloc[[0, 2]]

No.1    female
No.3      male
dtype: object

In [42]:
df = pd.DataFrame({'age': sr1, 'gender': sr2})
df

age  gender
No.1   53  female
No.2   64    male
No.3   72    male
No.4   82  female

In [43]:
v = np.array([[53, 'female'], [64, 'male'], [72, 'male'], [82, 'female']])
i = ['No.1', 'No.2', 'No.3', 'No.4']
c = ['age', 'gender']

In [44]:
df  = pd.DataFrame(v, index= i, columns= c)
df

age  gender
No.1  53  female
No.2  64    male
No.3  72    male
No.4  82  female

In [64]:
df.loc['No.1', 'gender']

'female'

In [65]:
df.loc[['No.1', 'No.3'], ['gender', 'age']]

gender age
No.1  female  53
No.3    male  72

In [45]:
df.values

array([['53', 'female'],
       ['64', 'male'],
       ['72', 'male'],
       ['82', 'female']], dtype=object)

In [46]:
df.columns

Index(['age', 'gender'], dtype='object')

In [47]:
df.index

Index(['No.1', 'No.2', 'No.3', 'No.4'], dtype='object')

In [49]:
arr = df.values
arr

array([['53', 'female'],
       ['64', 'male'],
       ['72', 'male'],
       ['82', 'female']], dtype=object)

In [50]:
arr = arr[:, 0].astype(int)
arr

array([53, 64, 72, 82])

In [66]:
v1 = [10, 20, 30, 40]
v2 = [40, 50, 60]
k1 = ['No.1', 'No.2', 'No.3', 'No.4']
k2 = ['No.4', 'No.5', 'No.6']
sr1 = pd.Series(v1, index= k1)
sr2 = pd.Series(v2, index= k2)
sr1, sr2

(No.1    10
 No.2    20
 No.3    30
 No.4    40
 dtype: int64,
 No.4    40
 No.5    50
 No.6    60
 dtype: int64)

In [68]:
sr3 = pd.concat([sr1, sr2])

In [69]:
sr3.index.is_unique

False

In [71]:
v1 = [53, 64, None, 82]
i = ['No.1', 'No.2', 'No.3', 'No.4']
sr = pd.Series(v1, index= i)
sr

No.1    53.0
No.2    64.0
No.3     NaN
No.4    82.0
dtype: float64

In [72]:
sr.dropna()

No.1    53.0
No.2    64.0
No.4    82.0
dtype: float64

In [78]:
v = np.array([[None, 'None'], [64, 'None'], [72, 'male'], [82, 'female']])
i = ['No.1', 'No.2', 'No.3', 'No.4']
c = ['age', 'gender']
df  = pd.DataFrame(v, index= i, columns= c)
df

age  gender
No.1  None    None
No.2    64    None
No.3    72    male
No.4    82  female

In [80]:
df.dropna()

age  gender
No.2  64    None
No.3  72    male
No.4  82  female

In [81]:
df.dropna(how= 'all')

age  gender
No.1  None    None
No.2    64    None
No.3    72    male
No.4    82  female