In [1]:
import torch
torch.__version__
device = torch.device('mps')

In [2]:
x = torch.empty(5, 3) # 创建一个5x3的未初始化的Tensor
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
x = torch.rand(5, 3) # 创建一个5x3的随机初始化的Tensor
x

tensor([[0.3126, 0.8072, 0.0764],
        [0.6804, 0.6662, 0.2391],
        [0.3524, 0.5613, 0.3996],
        [0.2621, 0.1728, 0.8901],
        [0.9029, 0.9270, 0.0930]])

In [4]:
x = torch.zeros(5, 3, dtype=torch.long) # 创建一个5x3的long型全0的Tensor
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
x = torch.tensor([5.5, 3]) # 直接根据数据创建
x

tensor([5.5000, 3.0000])

In [6]:
x = x.new_ones(5, 3, dtype=torch.double) # 根据已有的Tensor创建

x = torch.randn_like(x, dtype=torch.float) # 重载dtype
x

tensor([[ 0.1169,  0.8302, -0.6030],
        [-0.6853, -0.1917,  0.5298],
        [ 0.3337, -0.0140,  0.7356],
        [ 0.6372, -0.2157,  0.1742],
        [ 0.0748,  0.4324,  0.7463]])

In [7]:
x.size() # 查看x的形状

torch.Size([5, 3])

In [8]:
y = torch.rand(5, 3)
x + y

tensor([[0.3938, 1.4513, 0.1959],
        [0.2292, 0.5695, 0.8526],
        [1.1092, 0.0241, 1.3415],
        [0.8278, 0.0411, 1.1183],
        [0.2610, 1.2329, 1.1747]])

In [9]:
x[: , 1].reshape(-1, 1)

tensor([[ 0.8302],
        [-0.1917],
        [-0.0140],
        [-0.2157],
        [ 0.4324]])

In [10]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [11]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [12]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)