In [1]:
import torch
from torch import tensor


In [5]:
x = tensor(42)
x, x.dim()

(tensor(42), 0)

In [6]:
2 * x

tensor(84)

In [8]:
x.item()

42

In [10]:
v = tensor([1, 2, 3])
v, v.dim(), v.size()

(tensor([1, 2, 3]), 1, torch.Size([3]))

In [11]:
M = tensor([[1, 2, 3], [4, 5, 6]])
M, M.dim(), M.size()

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 2,
 torch.Size([2, 3]))

In [12]:
M * M

tensor([[ 1,  4,  9],
        [16, 25, 36]])